import { createClient } from '@supabase/supabase-js';
import fs from 'fs';
import path from 'path';

// Load env vars manually
const envPath = path.resolve('C:/Users/lych0/Downloads/ConnectEd/.env.local');
const envContent = fs.readFileSync(envPath, 'utf-8');

let supabaseUrl = '';
let supabaseKey = '';

envContent.split('\n').forEach(line => {
  const [key, ...rest] = line.split('=');
  const val = rest.join('=').trim();
  if (key.trim() === 'VITE_SUPABASE_URL') supabaseUrl = val;
  if (key.trim() === 'VITE_SUPABASE_ANON_KEY') supabaseKey = val;
});

const supabase = createClient(supabaseUrl, supabaseKey);

async function run() {
  console.log("Finding teacher juan.delacruz@dasma.deped.gov.ph...");
  const { data: users, error: userError } = await supabase
    .from('users')
    .select('*')
    .eq('email', 'juan.delacruz@dasma.deped.gov.ph');
    
  if (userError || !users?.length) {
    console.error("Teacher not found:", userError || "No users returned");
    return;
  }
  const teacherId = users[0].id;
  console.log("Teacher ID:", teacherId);

  console.log("Finding class 'Araling Panlipunan - Grade 10'...");
  const { data: classes, error: classError } = await supabase
    .from('subjects')
    .select('*')
    .eq('teacher_id', teacherId)
    .ilike('subject', '%Araling Panlipunan%')
    .ilike('grade_level', '%10%');

  if (classError || !classes?.length) {
    console.error("Class not found:", classError || "No classes returned");
    return;
  }
  const classId = classes[0].id;
  console.log("Class ID:", classId);

  console.log("Finding students in class...");
  const { data: enrollments, error: enrollError } = await supabase
    .from('student_subjects')
    .select('student_id, students(id, first_name, last_name)')
    .eq('subject_id', classId);

  if (enrollError || !enrollments?.length) {
    console.error("No students enrolled in this class:", enrollError || "No enrollments returned");
    return;
  }
  const student = enrollments[0].students;
  console.log("Selected Student:", student.first_name, student.last_name, `(${student.id})`);

  console.log("Finding an assignment/seatwork in this class...");
  const { data: assignments, error: asgError } = await supabase
    .from('assignments')
    .select('*')
    .eq('course_id', classId)
    .limit(1);

  if (asgError || !assignments?.length) {
    console.error("No assignments found for this class. Please create one first.");
    return;
  }
  const assignment = assignments[0];
  console.log("Selected Assignment:", assignment.title, `(${assignment.id})`);

  console.log("Creating submission in teacher_assessment_submissions...");
  const { data: subData, error: subError } = await supabase
    .from('teacher_assessment_submissions')
    .upsert({
      teacher_id: teacherId,
      subject_id: classId,
      assessment_id: assignment.id,
      student_id: student.id,
      status: 'Submitted',
      submitted_at: new Date().toISOString(),
      content: 'This is a test submission generated by the AI for testing the gradebook.',
      files: []
    }, { onConflict: 'teacher_id,subject_id,assessment_id,student_id' })
    .select();

  if (subError) {
    console.error("Error creating submission:", subError);
    return;
  }
  console.log("Successfully created submission!", subData);

  console.log("Creating grade record placeholder...");
  const { error: gradeError } = await supabase
    .from('teacher_assessment_grades')
    .upsert({
      teacher_id: teacherId,
      subject_id: classId,
      assessment_id: assignment.id,
      student_id: student.id,
      score: null, 
      feedback: null
    }, { onConflict: 'teacher_id,subject_id,assessment_id,student_id' });

  if (gradeError) {
    console.error("Error creating grade record:", gradeError);
  } else {
    console.log("Successfully created grade placeholder!");
  }
  
  console.log("Done seeding submission!");
}

run();
