export const ACADEMIC_SETTINGS_TOUR = {
  id: "academic-settings",
  moduleTitle: "Academic Settings",
  route: "/admin/academic-settings",
  steps: [
    {
      id: "settings-welcome",
      targetSelector: '[data-tour="settings-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to Academic Settings",
      description: "Configure active school years, current quarter terms, grade level thresholds, and class section limits.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "Settings configured here define the global parameters for all academic grading calculations.",
      placement: "bottom",
    },
    {
      id: "settings-school-year",
      targetSelector: '[data-tour="settings-school-year"]',
      fallbackTargetSelector: '[data-tour="settings-header"]',
      title: "School Year & Active Quarter",
      description: "Set the current active school year (e.g., 2025-2026) and active grading quarter (1st - 4th Quarter).",
      messageType: "warning",
      messageTitle: "Critical Setting",
      messageText: "Changing the active quarter controls which gradebook quarter teachers can submit grades for.",
      placement: "right",
    },
    {
      id: "settings-sections",
      targetSelector: '[data-tour="settings-sections-config"]',
      fallbackTargetSelector: '[data-tour="settings-school-year"]',
      title: "Current Quarter",
      description: "Select the active grading quarter. This controls which quarter teachers can enter and submit grades for.",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Always confirm the active quarter at the start of each grading period to avoid grade submission issues.",
      placement: "top",
    },
  ],
};
