export const ANNOUNCEMENTS_TOUR = {
  id: "announcements",
  moduleTitle: "Announcements & Broadcasts",
  route: "/admin/announcements",
  steps: [
    {
      id: "announcements-welcome",
      targetSelector: '[data-tour="announcements-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to Announcements",
      description: "Publish school-wide announcements, emergency alerts, and administrative broadcasts.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "Announcements published here appear immediately on teacher and student portal dashboards.",
      placement: "bottom",
    },
    {
      id: "announcements-create",
      targetSelector: '[data-tour="announcements-create-btn"]',
      fallbackTargetSelector: '[data-tour="announcements-header"]',
      title: "Create Announcement",
      description: "Draft official notices with rich text, target audience selection, and priority badges.",
      messageType: "tip",
      messageTitle: "Priority Levels",
      messageText: "Use 'High Priority' or 'Urgent' badges for immediate notices like class suspensions or exam schedules.",
      placement: "left",
    },
    {
      id: "announcements-search",
      targetSelector: '[data-tour="announcements-search"]',
      fallbackTargetSelector: '[data-tour="announcements-header"]',
      title: "Search Announcements",
      description: "Quickly find past announcements by title or content keyword.",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Search by title keyword to quickly locate and edit previously published notices.",
      placement: "bottom",
    },
    {
      id: "announcements-list",
      targetSelector: '[data-tour="announcements-list"]',
      fallbackTargetSelector: '[data-tour="announcements-header"]',
      title: "Announcement Feed",
      description: "Browse past broadcasts, check read metrics, edit published notices, or pin important updates.",
      messageType: "reminder",
      messageTitle: "Reminder",
      messageText: "Pinned announcements remain at the top of all user feeds until unpinned.",
      placement: "top",
    },
  ],
};
