export const CALENDAR_TOUR = {
  id: "calendar",
  moduleTitle: "School Calendar",
  route: "/admin/calendar",
  steps: [
    {
      id: "calendar-welcome",
      targetSelector: '[data-tour="calendar-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to School Calendar",
      description: "Manage academic schedules, examination periods, school holidays, and official events.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "Calendar events display across student and teacher portals to keep the school synchronized.",
      placement: "bottom",
    },
    {
      id: "calendar-add",
      targetSelector: '[data-tour="calendar-add-btn"]',
      fallbackTargetSelector: '[data-tour="calendar-header"]',
      title: "Add Event",
      description: "Schedule new academic events, quarterly exam dates, or official school holidays.",
      messageType: "reminder",
      messageTitle: "Reminder",
      messageText: "Marking an event as 'School Holiday' automatically alerts teachers regarding grade deadline adjustments.",
      placement: "left",
    },
    {
      id: "calendar-grid",
      targetSelector: '[data-tour="calendar-grid"]',
      fallbackTargetSelector: '[data-tour="calendar-add-btn"]',
      title: "School Events List",
      description: "View all upcoming school events and holidays. Click any event to edit or remove it from the calendar.",
      messageType: "tip",
      messageTitle: "Navigation Tip",
      messageText: "Use the filter toggles on the calendar to view specific event types like Examinations, Holidays, or Extracurriculars.",
      placement: "top",
    },
  ],
};
