export const DASHBOARD_TOUR = {
  id: "dashboard",
  moduleTitle: "Dashboard Overview",
  route: "/admin/dashboard",
  steps: [
    {
      id: "dashboard-welcome",
      targetSelector: '[data-tour="dashboard-overview"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to ConnectED Command Center",
      description: "Get an instant summary of active academic parameters, school terms, and core operations.",
      messageType: "info",
      messageTitle: "System Status",
      messageText: "The active school year and grading quarter display at the top right for quick reference.",
      placement: "bottom",
    },
    {
      id: "dashboard-stats",
      targetSelector: '[data-tour="dashboard-stats"]',
      fallbackTargetSelector: '[data-tour="dashboard-overview"]',
      title: "Live Key Performance Indicators",
      description: "Monitor enrolled student counts, active teaching staff profiles, and configured subject courses.",
      messageType: "tip",
      messageTitle: "Live Database Metrics",
      messageText: "Counts update automatically in real-time whenever new users register or courses are added.",
      placement: "bottom",
    },
    {
      id: "dashboard-resets",
      targetSelector: '[data-tour="dashboard-resets-stat"]',
      fallbackTargetSelector: '[data-tour="dashboard-stats"]',
      title: "Pending Password Resets",
      description: "Quickly view and resolve student and teacher temporary password reset requests.",
      messageType: "warning",
      messageTitle: "Action Item",
      messageText: "Clicking this card takes you directly to the Password Reset Requests management panel.",
      placement: "bottom",
    },
    {
      id: "dashboard-activity",
      targetSelector: '[data-tour="dashboard-activity"]',
      fallbackTargetSelector: '[data-tour="dashboard-overview"]',
      title: "Real-Time Activity Audit Trail",
      description: "Review a live chronological log of all administrative actions, profile updates, and system events.",
      messageType: "reminder",
      messageTitle: "Audit Compliance",
      messageText: "Every account creation, section assignment, and password change is timestamped for security.",
      placement: "top",
    },
    {
      id: "dashboard-notifications",
      targetSelector: '[data-tour="dashboard-notifications"]',
      fallbackTargetSelector: '[data-tour="dashboard-overview"]',
      title: "Real-Time System Notifications",
      description: "Access instant administrative alerts, unread message badges, and system update broadcasts.",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Check notification alerts daily to stay informed on system activity and account requests.",
      placement: "left",
    },
  ],
};
