export const REPORTS_TOUR = {
  id: "reports",
  moduleTitle: "Reports & Analytics",
  route: "/admin/reports",
  steps: [
    {
      id: "reports-welcome",
      targetSelector: '[data-tour="reports-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to Reports & Analytics",
      description: "Generate administrative reports, monitor enrollment statistics, and export academic performance summaries.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "Access consolidated school statistics formatted for DepEd compliance and administrative reviews.",
      placement: "bottom",
    },
    {
      id: "reports-enrollment",
      targetSelector: '[data-tour="reports-enrollment-card"]',
      title: "Enrollment Summary",
      description: "Review total student distribution across Grade 7 to 10 and track male/female ratio metrics.",
      messageType: "info",
      messageTitle: "Demographic Data",
      messageText: "Data automatically updates whenever new students are registered or assigned sections.",
      placement: "bottom",
    },
    {
      id: "reports-faculty",
      targetSelector: '[data-tour="reports-faculty-card"]',
      title: "Faculty Workload Reports",
      description: "Monitor teacher subject loads, class section counts, and gradebook submission completion rates.",
      messageType: "tip",
      messageTitle: "Workload Monitoring",
      messageText: "Identify overloaded or unassigned faculty before finalizing quarterly class schedules.",
      placement: "bottom",
    },
    {
      id: "reports-export",
      targetSelector: '[data-tour="reports-export-btn"]',
      title: "Export & Print Reports",
      description: "Download official administrative summaries in PDF or Excel/CSV format.",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Export quarterly summary reports at the close of every grading period for official school archives.",
      placement: "left",
    },
  ],
};
