export const STUDENT_TOUR = {
  id: "students",
  moduleTitle: "Student Management",
  route: "/admin/students",
  steps: [
    {
      id: "students-welcome",
      targetSelector: '[data-tour="students-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to Student Management",
      description: "Manage student accounts, registration, section assignments, LRN verification, and academic profiles.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "Use this module as your centralized student database for all registered junior high school students.",
    },
    {
      id: "students-import",
      targetSelector: '[data-tour="students-import-btn"]',
      fallbackTargetSelector: '[data-tour="students-header"]',
      title: "Import Student Masterlist",
      description: "Bulk import student enrolment records using official DepEd CSV spreadsheet templates.",
      messageType: "tip",
      messageTitle: "Importing Tip",
      messageText: "Ensure LRN, full name, and birth dates match DepEd SF-1 records before uploading your CSV file.",
    },
    {
      id: "students-add",
      targetSelector: '[data-tour="students-add-btn"]',
      fallbackTargetSelector: '[data-tour="students-header"]',
      title: "Add Individual Student",
      description: "Register a new student account manually by entering their official LRN, complete name, email, and grade assignment.",
      messageType: "reminder",
      messageTitle: "Reminder",
      messageText: "Verify that the student's 12-digit LRN is accurate to prevent duplicate student profiles.",
    },
    {
      id: "students-filter",
      targetSelector: '[data-tour="students-filters"]',
      title: "Grade & Section Filters",
      description: "Filter student lists by grade level (Grade 7 - 10), class section, or account status (Active / Inactive).",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Apply Grade Level filters first before searching large student lists to speed up lookup performance.",
    },
    {
      id: "students-search",
      targetSelector: '[data-tour="students-search"]',
      title: "Search Students Bar",
      description: "Quickly locate student records by entering a student's name, email, or LRN (Learner Reference Number).",
      messageType: "tip",
      messageTitle: "Search Tip",
      messageText: "You can type partial names or LRNs for instant filtering without pressing Enter.",
      placement: "right",
    },
    {
      id: "students-export",
      targetSelector: '[data-tour="students-export-btn"]',
      fallbackTargetSelector: '[data-tour="students-search"]',
      title: "Export Roster Records",
      description: "Download filtered student roster data as a CSV file for official DepEd reporting and administrative archives.",
      messageType: "info",
      messageTitle: "Export Info",
      messageText: "Exported files include student names, LRNs, grade assignments, section codes, and active statuses.",
    },
    {
      id: "students-row",
      targetSelector: '[data-tour="students-row"]',
      fallbackTargetSelector: '[data-tour="students-table"]',
      title: "Student Roster Profile Row",
      description: "Each row represents a registered student profile with LRN, email address, assigned grade, and enrolment date.",
      messageType: "info",
      messageTitle: "Student Profile Row",
      messageText: "Select individual check-boxes to perform bulk deletions or section re-assignments.",
    },
    {
      id: "students-status-badge",
      targetSelector: '[data-tour="students-status-badge"]',
      fallbackTargetSelector: '[data-tour="students-row"]',
      title: "Account Verification Status",
      description: "Indicates whether the student account is Active, Pending Verification, or Deactivated.",
      messageType: "best_practice",
      messageTitle: "Status Guide",
      messageText: "Green badges indicate active student accounts; red or gray badges indicate restricted portal access.",
    },
    {
      id: "students-actions",
      targetSelector: '[data-tour="students-actions"]',
      title: "Student Actions Menu",
      description: "Access student options: view full profile details, edit account information, reset passwords, or deactivate accounts.",
      messageType: "warning",
      messageTitle: "Warning",
      messageText: "Deactivating or deleting a student profile will restrict their portal login and gradebook history.",
    },
    {
      id: "students-masterlist",
      targetSelector: '[data-tour="students-masterlist-tab"]',
      title: "Masterlist & Section Assignment",
      description: "Switch to the Masterlist tab to bulk assign unassigned students to specific class sections.",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Run section assignments at the start of each semester to ensure teachers see all students in their gradebook.",
    },
  ],
};
