export const SUBJECT_TOUR = {
  id: "subjects",
  moduleTitle: "Subject Management",
  route: "/admin/subjects",
  steps: [
    {
      id: "subjects-welcome",
      targetSelector: '[data-tour="subjects-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to Subject Management",
      description: "Create and configure subjects, set up subject codes, and map curriculum courses to grade levels.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "All subject definitions configured here populate the DepEd curriculum offerings across Grade 7 to 10.",
      placement: "bottom",
    },
    {
      id: "subjects-search",
      targetSelector: '[data-tour="subjects-search"]',
      title: "Search Subjects",
      description: "Locate subjects by subject code (e.g. MATH-7, ENG-8), title, or grade level designation.",
      messageType: "tip",
      messageTitle: "Search Tip",
      messageText: "Use subject code prefixes (e.g. AP-, SCI-, MAPEH-) to group subject offerings by department.",
      placement: "bottom",
    },
    {
      id: "subjects-add",
      targetSelector: '[data-tour="subjects-add-btn"]',
      title: "Add Subject",
      description: "Define a new subject offering with subject code, title, grade level assignment, and department category.",
      messageType: "reminder",
      messageTitle: "Reminder",
      messageText: "DepEd grading formulas vary by subject category (e.g. Languages vs Sciences). Select the correct category.",
      placement: "left",
    },
    {
      id: "subjects-list",
      targetSelector: '[data-tour="subjects-list"]',
      title: "Subject Catalog",
      description: "View all active subjects categorized by grade level and assigned subject lead teachers.",
      messageType: "info",
      messageTitle: "Catalog Info",
      messageText: "Each subject card shows total enrolled students and mapped teacher assignments.",
      placement: "top",
    },
    {
      id: "subjects-actions",
      targetSelector: '[data-tour="subjects-actions"]',
      title: "Subject Actions",
      description: "Edit subject parameters, update grading component weights, or manage assigned section teachers.",
      messageType: "warning",
      messageTitle: "Warning",
      messageText: "Modifying a subject's grading category will update quarterly grade calculations for all linked classes.",
      placement: "left",
    },
  ],
};
