export const TEACHER_GRADES_TOUR = {
  moduleId: "grades",
  moduleTitle: "Grades Management",
  route: "/teacher/grades",
  steps: [
    {
      id: "grades-header",
      targetSelector: '[data-tour="teacher-grades-header"]',
      fallbackTargetSelector: 'h1',
      title: "DepEd Grade Management Overview",
      description: "Welcome to the Gradebook. Encode student raw scores and generate official DepEd transmuted grades automatically.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Gradebook Command Center",
      messageText: "Manage student assessment marks and DepEd transmuted quarterly grades.",
    },
    {
      id: "grades-class-select",
      targetSelector: '[data-tour="teacher-grades-class-select"]',
      fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
      title: "Select Class Section",
      description: "Choose a subject and section from the dropdown list to load its student roster and grade matrix.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Section Selector",
      messageText: "Select your active class section to view student grades.",
    },
    {
      id: "grades-search",
      targetSelector: '[data-tour="teacher-grades-search"]',
      fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
      title: "Student Search",
      description: "Find specific students quickly by typing their full name or Learner Reference Number (LRN).",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Student Search Input",
      messageText: "Filter student grade rows by name or LRN.",
    },
    {
      id: "grades-filters",
      targetSelector: '[data-tour="teacher-grades-filters"]',
      fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
      title: "Quarter & Assessment Filter Tabs",
      description: "Switch between 1st–4th Quarters (Q1–Q4), filter assessment components (Quizzes, Activities, Exams), or view Passed vs Failed students.",
      placement: "bottom",
      messageType: "tip",
      messageTitle: "Flexible View Filters",
      messageText: "Filter grade columns by academic term or assessment type.",
    },
    {
      id: "grades-table",
      targetSelector: '[data-tour="teacher-grades-table"]',
      fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
      title: "DepEd Gradebook Matrix Table",
      description: "View student LRNs, quarter scores, quiz averages, activity marks, overall percentages, and automatic DepEd passing remarks (Passed / Failed).",
      placement: "top",
      messageType: "tip",
      messageTitle: "Auto-Consolidated Matrix",
      messageText: "DepEd transmutation applies automatically to raw scores.",
    },
    {
      id: "grades-seatworks-eval",
      targetSelector: '[data-tour="teacher-grades-seatworks-eval"]',
      fallbackTargetSelector: '[data-tour="teacher-grades-seatworks-header"]',
      title: "Activity-Based Performance Evaluation",
      description: "Review seatworks, quizzes, performance tasks, and periodical exams. Select any seatwork or student row to inspect individual submissions.",
      placement: "right",
      messageType: "info",
      messageTitle: "Seatworks & Activities Roster",
      messageText: "Inspect seatworks and student submission statuses in real time.",
    },
    {
      id: "grades-submission-detail",
      targetSelector: '[data-tour="teacher-grades-submission-detail"]',
      fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
      title: "Student Submission & Grade Evaluation",
      description: "Inspect submitted student outputs, enter or lock raw scores, write teacher feedback comments, and return grades directly to students.",
      placement: "top",
      messageType: "tip",
      messageTitle: "Score & Feedback Evaluation",
      messageText: "Input raw scores, lock grades, and return feedback to students.",
    },
  ],
};
