export const TEACHER_DASHBOARD_TOUR = {
  moduleId: "teacher-dashboard",
  moduleTitle: "Teacher Dashboard",
  route: "/teacher/dashboard",
  steps: [
    {
      id: "dashboard-welcome",
      targetSelector: '[data-tour="teacher-dashboard-header"]',
      title: "Teacher Dashboard Overview",
      description: "Monitor current School Year, Quarter status, and daily teaching schedule.",
      placement: "bottom-left",
      messageType: "info",
      messageTitle: "Teaching Overview",
      messageText: "View current academic quarter status and class counts.",
    },
    {
      id: "dashboard-kpis",
      targetSelector: '[data-tour="teacher-kpis"]',
      title: "Teaching Statistics & KPIs",
      description: "Track total assigned classes, enrolled students, published lessons, draft materials, and recorded grades.",
      placement: "bottom-right",
      messageType: "tip",
      messageTitle: "Live Metrics",
      messageText: "Monitor student enrollment and lesson publishing progress.",
    },
    {
      id: "dashboard-tasks",
      targetSelector: '[data-tour="teacher-tasks"]',
      fallbackTargetSelector: '[data-tour="teacher-dashboard-header"]',
      title: "Tasks & Deadline Management",
      description: "Keep track of pending seatworks, assignments needing grading, and upcoming quiz deadlines for your subjects.",
      placement: "right",
      messageType: "info",
      messageTitle: "Classroom Task Overview",
      messageText: "Monitor due tasks and student submissions needing your review.",
    },
    {
      id: "dashboard-recent-grades",
      targetSelector: '[data-tour="teacher-recent-grades"]',
      fallbackTargetSelector: '[data-tour="teacher-dashboard-header"]',
      title: "Recently Updated Grades",
      description: "View real-time student grade recordings, recent score updates, and percentage marks calculated for your subject sections.",
      placement: "left",
      messageType: "tip",
      messageTitle: "Live Score Activity",
      messageText: "Track newly recorded student grades and quarterly mark updates.",
    },
    {
      id: "dashboard-announcements",
      targetSelector: '[data-tour="teacher-announcements"]',
      title: "School Announcements & Memos",
      description: "Stay informed with official DepEd school-wide broadcasts, emergency memo updates, and administrative announcements.",
      placement: "top",
      messageType: "info",
      messageTitle: "School Bulletins",
      messageText: "Read official school announcements and view attached PDF/image documents.",
    },
    {
      id: "dashboard-calendar",
      targetSelector: '[data-tour="teacher-calendar"]',
      title: "Academic Calendar & Schedule",
      description: "Keep track of upcoming exam schedules, grade submission deadlines, school holidays, and institutional events.",
      placement: "left",
      messageType: "tip",
      messageTitle: "Calendar & Events",
      messageText: "View scheduled exam dates and school holidays.",
    },
  ],
};
