export const TEACHER_ANNOUNCEMENTS_TOUR = {
  moduleId: "teacher-announcements",
  moduleTitle: "Announcements & Broadcasts",
  route: "/teacher/announcements",
  steps: [
    {
      id: "announcements-header",
      targetSelector: '[data-tour="teacher-announcements-header"]',
      fallbackTargetSelector: 'h1',
      title: "Class Content & Announcement Hub",
      description: "Publish official section notices, post homework assignments, and share class learning materials with enrolled students.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Content Management",
      messageText: "Share announcements, assignments, and class files.",
    },
    {
      id: "announcements-tabs",
      targetSelector: '[data-tour="teacher-announcements-tabs"]',
      fallbackTargetSelector: '[data-tour="teacher-announcements-header"]',
      title: "Content Category Tabs",
      description: "Switch seamlessly between Announcements, Homework Assignments, and Downloadable Resource Files.",
      placement: "bottom",
      messageType: "tip",
      messageTitle: "Category Tabs",
      messageText: "Filter published content by announcements, assignments, or files.",
    },
    {
      id: "announcements-list",
      targetSelector: '[data-tour="teacher-announcements-list"]',
      fallbackTargetSelector: '[data-tour="teacher-announcements-header"]',
      title: "Class Bulletins & Materials List",
      description: "View active broadcasts, review student submission counts, and manage attached file resources.",
      placement: "top",
      messageType: "tip",
      messageTitle: "Bulletins Roster",
      messageText: "Inspect posted notices and student file attachments.",
    },
    {
      id: "announcements-create-btn",
      targetSelector: '[data-tour="teacher-announcements-create-btn"]',
      fallbackTargetSelector: '[data-tour="teacher-announcements-header"]',
      title: "Post New Content",
      description: "Click to compose a new announcement notice, post an assignment, or upload a class document.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Create & Publish",
      messageText: "Publish new announcements or upload class resources.",
    },
  ],
};
