export const TEACHER_AI_TOUR = {
  moduleId: "ai-assistant",
  moduleTitle: "AI Teaching Assistant",
  route: "/teacher/ai-assistant",
  steps: [
    {
      id: "ai-header",
      targetSelector: '[data-tour="teacher-ai-header"]',
      fallbackTargetSelector: 'h2',
      title: "AI Educator Copilot",
      description: "Generate complete, DepEd-aligned lesson plans, quiz items, rubrics, and classroom activities tailored for your active subject.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "AI Lesson Copilot",
      messageText: "Generate curriculum-aligned teaching materials in seconds.",
    },
    {
      id: "ai-upload-zone",
      targetSelector: '[data-tour="teacher-ai-upload-zone"]',
      fallbackTargetSelector: '[data-tour="teacher-ai-header"]',
      title: "Class Materials Upload Zone",
      description: "Upload PDFs, Word documents, PowerPoint slides, or text files to train the AI assistant on your exact lesson material.",
      placement: "right",
      messageType: "tip",
      messageTitle: "Document Context Loader",
      messageText: "Drag & drop lesson files for context-aware generation.",
    },
    {
      id: "ai-toolbar",
      targetSelector: '[data-tour="teacher-ai-toolbar"]',
      fallbackTargetSelector: '[data-tour="teacher-ai-header"]',
      title: "Quick Deliverables Toolbar",
      description: "Click 1-tap shortcuts to generate Quizzes, Lesson Plans, Discussion Prompts, Activity Rubrics, or Summaries instantly.",
      placement: "right",
      messageType: "tip",
      messageTitle: "1-Tap Deliverable Generators",
      messageText: "Select a prompt template to start building teaching resources.",
    },
    {
      id: "ai-chat-workspace",
      targetSelector: '[data-tour="teacher-ai-chat-workspace"]',
      fallbackTargetSelector: '[data-tour="teacher-ai-header"]',
      title: "Interactive Chat & Output Workspace",
      description: "Chat with the AI assistant to refine lesson plans, ask subject questions, select active classes, and export generated outputs.",
      placement: "left",
      messageType: "info",
      messageTitle: "Live AI Workspace",
      messageText: "Type custom instructions or ask AI to revise generated items.",
    },
  ],
};
