export const TEACHER_CLASS_DETAIL_TOUR = {
  moduleId: "class-detail",
  moduleTitle: "Class Detail & Content",
  route: "/teacher/classes",
  steps: [
    {
      id: "class-detail-banner",
      targetSelector: '[data-tour="teacher-class-banner"]',
      fallbackTargetSelector: 'h1',
      title: "Class Banner & Metrics",
      description: "Displays the active subject code, section title, schedule, room, and quick stats for enrolled students, published lessons, quizzes, and assignments.",
      placement: "bottom-left",
      messageType: "info",
      messageTitle: "Class Command Center",
      messageText: "Monitor class section details and activity counts.",
    },
    {
      id: "class-detail-tabs",
      targetSelector: '[data-tour="teacher-class-tabs"]',
      fallbackTargetSelector: 'h1',
      title: "Class Content Navigation Tabs",
      description: "Switch between the Students roster tab, Lessons & Learning Materials tab, and Section Announcements tab.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Content Navigation",
      messageText: "Manage enrolled students, AI lessons, and class notices.",
    },
    {
      id: "class-detail-students",
      targetSelector: '[data-tour="class-detail-students-list"]',
      fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
      title: "Enrolled Student Roster",
      description: "Inspect student LRNs, full names, contact info, and parent details. Search for specific students or add new section enrollments.",
      placement: "top",
      messageType: "tip",
      messageTitle: "Student Roster",
      messageText: "View enrolled student profiles and contact information.",
    },
    {
      id: "class-detail-lessons",
      targetSelector: '[data-tour="class-detail-lessons-content"]',
      fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
      title: "Lessons & AI Generator",
      description: "Create and publish structured lesson plans, upload class materials, and generate AI quiz items tailored for this section.",
      placement: "top",
      messageType: "warning",
      messageTitle: "AI Lesson & Quiz Generator",
      messageText: "Publish curriculum-aligned lessons and study resources.",
    },
    {
      id: "class-detail-announcements",
      targetSelector: '[data-tour="class-detail-announcements-content"]',
      fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
      title: "Class Announcements & Memos",
      description: "Post class notices, exam reminders, and homework assignments directly to all enrolled students in this section.",
      placement: "top",
      messageType: "info",
      messageTitle: "Section Bulletins",
      messageText: "Broadcast section-specific notices and attach file resources.",
    },
  ],
};
