export const TEACHER_TOUR = {
  id: "teachers",
  moduleTitle: "Teacher Management",
  route: "/admin/teachers",
  steps: [
    {
      id: "teachers-welcome",
      targetSelector: '[data-tour="teachers-header"]',
      fallbackTargetSelector: '[data-tour="sidebar"]',
      title: "Welcome to Teacher Management",
      description: "Manage faculty profiles, teacher account activations, subject assignments, and class workloads.",
      messageType: "info",
      messageTitle: "Overview",
      messageText: "Use this module to verify teaching staff accounts and assign subjects to subject teachers.",
      placement: "bottom",
    },
    {
      id: "teachers-search",
      targetSelector: '[data-tour="teachers-search"]',
      title: "Search Faculty",
      description: "Search teachers by full name, email address, or assigned department subject.",
      messageType: "tip",
      messageTitle: "Search Tip",
      messageText: "Filter by active status to quickly identify newly registered teachers awaiting account verification.",
      placement: "right",
    },
    {
      id: "teachers-add",
      targetSelector: '[data-tour="teachers-add-btn"]',
      title: "Add Teacher",
      description: "Register a new teacher profile manually and issue temporary login credentials.",
      messageType: "reminder",
      messageTitle: "Reminder",
      messageText: "Ensure the teacher's DepEd official email address is entered correctly for account notifications.",
      placement: "left",
    },
    {
      id: "teachers-table",
      targetSelector: '[data-tour="teachers-table"]',
      title: "Faculty Table",
      description: "Review teaching staff profiles, verification status, assigned subjects, and active class loads.",
      messageType: "info",
      messageTitle: "Status Indicators",
      messageText: "Verified teachers can immediately access their class gradebooks, lesson builders, and announcements.",
      placement: "top",
    },
    {
      id: "teachers-assignments",
      targetSelector: '[data-tour="teachers-assignments-btn"]',
      fallbackTargetSelector: '[data-tour="teachers-actions"]',
      title: "Subject & Section Assignments",
      description: "Click the edit icon (✏️) next to a teacher to open their profile and assign subject courses and class sections so they can manage their gradebooks.",
      messageType: "best_practice",
      messageTitle: "Best Practice",
      messageText: "Verify subject capacity limits before assigning teachers to multiple class sections.",
      placement: "left",
    },
    {
      id: "teachers-actions",
      targetSelector: '[data-tour="teachers-actions"]',
      fallbackTargetSelector: '[data-tour="teachers-table"]',
      title: "Teacher Profile Actions",
      description: "View faculty details, update contact information, reset temporary passwords, or manage verification status.",
      messageType: "warning",
      messageTitle: "Warning",
      messageText: "Deactivating a teacher account revokes their access to student grade submission tools.",
      placement: "left",
    },
  ],
};
