export const TEACHER_PROFILE_TOUR = {
  moduleId: "teacher-profile",
  moduleTitle: "Profile & Security",
  route: "/teacher/profile",
  steps: [
    {
      id: "profile-card",
      targetSelector: '[data-tour="teacher-profile-card"]',
      fallbackTargetSelector: 'h2',
      title: "Teacher Profile Overview",
      description: "View your official teacher avatar, full name, DepEd email address, teacher role, and active status badge.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Teacher Identity Profile",
      messageText: "Overview of your teacher credentials and status.",
    },
    {
      id: "profile-personal-info",
      targetSelector: '[data-tour="teacher-profile-personal-info"]',
      fallbackTargetSelector: '[data-tour="teacher-profile-card"]',
      title: "Personal & Contact Information",
      description: "Manage your contact phone number, teacher ID, full name, and assigned DepEd division details.",
      placement: "top",
      messageType: "tip",
      messageTitle: "Contact Details",
      messageText: "Keep your contact phone number and information up to date.",
    },
    {
      id: "profile-security-tab",
      targetSelector: '[data-tour="teacher-profile-security-tab"]',
      fallbackTargetSelector: '[data-tour="teacher-profile-card"]',
      title: "Account Security & Password",
      description: "Switch to the Security tab to update your account password, manage login sessions, and review account security.",
      placement: "bottom",
      messageType: "warning",
      messageTitle: "Password & Security",
      messageText: "Update your password regularly to protect student records.",
    },
  ],
};
