export const TEACHER_CLASSES_TOUR = {
  moduleId: "classes",
  moduleTitle: "Classes & Class Content",
  route: "/teacher/classes",
  steps: [
    {
      id: "classes-header",
      targetSelector: '[data-tour="teacher-classes-header"]',
      fallbackTargetSelector: 'h1',
      title: "My Classes Overview",
      description: "View all assigned subject sections for the active academic semester and school year.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Assigned Classes",
      messageText: "Manage your assigned class sections and view student rosters.",
    },
    {
      id: "classes-search",
      targetSelector: '[data-tour="teacher-classes-search"]',
      fallbackTargetSelector: '[data-tour="teacher-classes-header"]',
      title: "Class Search & Filter",
      description: "Type any course code or subject title to quickly locate a specific section.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Search Input",
      messageText: "Filter your class list instantly as you type.",
    },
    {
      id: "classes-grid",
      targetSelector: '[data-tour="teacher-classes-grid"]',
      fallbackTargetSelector: '[data-tour="teacher-classes-header"]',
      title: "Class Cards & Enrollment Metrics",
      description: "Each card displays the course code, subject name, section, schedule, and total enrolled students.",
      placement: "top",
      messageType: "tip",
      messageTitle: "Class Roster Overview",
      messageText: "Click on any class card or 'Proceed to View Class' to open its detailed roster and learning materials.",
    },
    {
      id: "classes-view-btn",
      targetSelector: '[data-tour="teacher-classes-view-btn"]',
      fallbackTargetSelector: '[data-tour="teacher-classes-header"]',
      title: "View Class Details",
      description: "Click 'Proceed to View Class' to navigate into this section's dashboard and explore student rosters, AI lessons, and announcements.",
      placement: "top",
      messageType: "info",
      messageTitle: "Interactive Navigation",
      messageText: "Opens the dedicated class section dashboard.",
      actionToRoute: "auto-first-class",
      actionButtonText: "Proceed to View Class",
    },
    {
      id: "class-detail-banner",
      targetSelector: '[data-tour="teacher-class-banner"]',
      fallbackTargetSelector: 'h1',
      title: "Class Banner & Quick Metrics",
      description: "Inside the class view! Displays active subject details, section title, schedule, room, and live student/lesson metrics.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Class Section Dashboard",
      messageText: "Monitor class section details and activity counts.",
    },
    {
      id: "class-detail-tabs",
      targetSelector: '[data-tour="teacher-class-tabs"]',
      fallbackTargetSelector: 'h1',
      title: "Class Content Navigation Tabs",
      description: "Switch between the Students roster tab, Lessons & Learning Materials tab, and Section Announcements tab.",
      placement: "bottom",
      messageType: "info",
      messageTitle: "Content Navigation",
      messageText: "Manage enrolled students, AI lessons, and class notices.",
    },
    {
      id: "class-detail-students",
      targetSelector: '[data-tour="class-detail-students-list"]',
      fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
      title: "Enrolled Student Roster",
      description: "Inspect student LRNs, full names, contact info, and parent details. Search for specific students or add new section enrollments.",
      placement: "top",
      messageType: "tip",
      messageTitle: "Student Roster",
      messageText: "View enrolled student profiles and contact information.",
    },
    {
      id: "class-detail-lessons",
      targetSelector: '[data-tour="class-detail-lessons-content"]',
      fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
      title: "Lessons & AI Generator",
      description: "Create and publish structured lesson plans, upload class materials, and generate AI quiz items tailored for this section.",
      placement: "top",
      messageType: "warning",
      messageTitle: "AI Lesson & Quiz Generator",
      messageText: "Publish curriculum-aligned lessons and study resources.",
    },
    {
      id: "class-detail-announcements",
      targetSelector: '[data-tour="class-detail-announcements-content"]',
      fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
      title: "Class Announcements & Memos",
      description: "Post class notices, exam reminders, and homework assignments directly to all enrolled students in this section.",
      placement: "top",
      messageType: "info",
      messageTitle: "Section Bulletins",
      messageText: "Broadcast section-specific notices and attach file resources.",
    },
  ],
};
