export const ADMIN_TOUR_STEPS = [
  {
    id: "sidebar-navigation",
    targetSelector: '[data-tour="sidebar"]',
    title: "Navigation Menu",
    description: "Use the sidebar to access every administrative module in the system.",
    placement: "right",
  },
  {
    id: "dashboard",
    targetSelector: '[data-tour="nav-dashboard"]',
    title: "Dashboard",
    description: "View important school statistics, real-time activity logs, and system alerts.",
    placement: "right",
  },
  {
    id: "student-management",
    targetSelector: '[data-tour="nav-students"]',
    title: "Student Management",
    description: "Manage student accounts, registrations, section assignments, and academic profiles.",
    placement: "right",
  },
  {
    id: "teacher-management",
    targetSelector: '[data-tour="nav-teachers"]',
    title: "Teacher Management",
    description: "Create teacher profiles, verify credentials, and assign teachers to subjects and sections.",
    placement: "right",
  },
  {
    id: "subject-management",
    targetSelector: '[data-tour="nav-subjects"]',
    title: "Subject Management",
    description: "Create and configure subjects, courses, and grade level curriculum assignments.",
    placement: "right",
  },
  {
    id: "announcements",
    targetSelector: '[data-tour="nav-announcements"]',
    title: "Announcements",
    description: "Publish school-wide announcements visible to all teachers and students.",
    placement: "right",
  },
  {
    id: "reports",
    targetSelector: '[data-tour="nav-reports"]',
    title: "Reports",
    description: "Generate administrative reports and monitor academic performance metrics.",
    placement: "right",
  },
  {
    id: "messages",
    targetSelector: '[data-tour="nav-messages"]',
    title: "Messages",
    description: "Communicate directly with teachers, students, and system users.",
    placement: "right",
  },
  {
    id: "school-calendar",
    targetSelector: '[data-tour="nav-calendar"]',
    title: "School Calendar",
    description: "Manage academic events, examination dates, and official school holidays.",
    placement: "right",
  },
  {
    id: "academic-settings",
    targetSelector: '[data-tour="nav-academic-settings"]',
    title: "Academic Settings",
    description: "Configure grade levels, class sections, school years, and quarter terms.",
    placement: "right",
  },
  {
    id: "help-center",
    targetSelector: '[data-tour="nav-help-center"]',
    title: "Help Center",
    description: "Access user guides, FAQs, contact support, and restart this guided tour anytime.",
    placement: "right",
  },
  {
    id: "tour-finish",
    targetSelector: null,
    title: "You're Ready!",
    description: "Congratulations! You have completed the ConnectED Administrator Tour.\n\nYou can restart this tour anytime through the Help menu.",
    isFinalStep: true,
    finishButtonText: "Finish",
  },
];
