export const TEACHER_TOUR_STEPS = [
  // ─── 1. TEACHER DASHBOARD WALKTHROUGH ─────────────────────
  {
    id: "teacher-dashboard-header",
    targetSelector: '[data-tour="teacher-dashboard-header"]',
    title: "Teacher Command Center",
    description: "Welcome to your command center! Here you can quickly view the active School Year, current Quarter, and a summary of your daily teaching responsibilities.",
    placement: "bottom",
    messageType: "info",
    messageTitle: "Academic Quarter Status",
    messageText: "Monitor current school year status and daily class schedules at a glance.",
  },
  {
    id: "teacher-kpis",
    targetSelector: '[data-tour="teacher-kpis"]',
    title: "Teaching Statistics & KPI Cards",
    description: "These KPI cards display your real-time academic metrics including assigned classes, enrolled students, published lessons, draft materials, and recorded grades.",
    placement: "bottom-right",
    messageType: "tip",
    messageTitle: "Live Class Analytics",
    messageText: "Track student enrollment counts and lesson publishing progress in real time.",
  },
  {
    id: "teacher-tasks",
    targetSelector: '[data-tour="teacher-tasks"]',
    fallbackTargetSelector: '[data-tour="teacher-dashboard-header"]',
    title: "Tasks & Deadline Management",
    description: "Keep track of pending seatworks, assignments needing grading, and upcoming quiz deadlines for your subjects.",
    placement: "right",
    messageType: "info",
    messageTitle: "Classroom Task Overview",
    messageText: "Monitor due tasks and student submissions needing your review.",
  },
  {
    id: "teacher-recent-grades",
    targetSelector: '[data-tour="teacher-recent-grades"]',
    fallbackTargetSelector: '[data-tour="teacher-dashboard-header"]',
    title: "Recently Updated Grades",
    description: "View real-time student grade recordings, recent score updates, and percentage marks calculated for your subject sections.",
    placement: "left",
    messageType: "tip",
    messageTitle: "Live Score Activity",
    messageText: "Track newly recorded student grades and quarterly mark updates.",
  },
  {
    id: "teacher-announcements",
    targetSelector: '[data-tour="teacher-announcements"]',
    title: "School Announcements & Memos",
    description: "Stay informed with official DepEd school-wide broadcasts, emergency memo updates, and administrative announcements.",
    placement: "top",
    messageType: "info",
    messageTitle: "School Bulletins",
    messageText: "Read official school announcements and view attached PDF/image documents.",
  },
  {
    id: "teacher-calendar",
    targetSelector: '[data-tour="teacher-calendar"]',
    title: "Academic Calendar & Schedule",
    description: "Keep track of upcoming exam schedules, grade submission deadlines, school holidays, and institutional events.",
    placement: "left",
    messageType: "tip",
    messageTitle: "Interactive Schedule",
    messageText: "Never miss a grade submission deadline or scheduled school activity.",
  },

  // ─── 2. MY CLASSES & CLASS DETAILS ──────────────────────────
  {
    id: "teacher-classes-link",
    targetSelector: '[data-tour="teacher-classes-link"]',
    title: "My Classes & Section Management",
    description: "Access your assigned subject sections, view enrolled student rosters, organize learning materials, and manage class schedules.",
    placement: "right",
    messageType: "info",
    messageTitle: "Class Management Hub",
    messageText: "Click 'Next' or click here to navigate to your assigned class list.",
    actionToRoute: "/teacher/classes",
  },
  {
    id: "teacher-classes-search",
    targetSelector: '[data-tour="teacher-classes-search"]',
    fallbackTargetSelector: '[data-tour="teacher-classes-header"]',
    title: "Filter & Search Classes",
    description: "Quickly filter your assigned classes by course code, subject name, or grade section.",
    placement: "bottom",
    messageType: "info",
    messageTitle: "Instant Class Filtering",
    messageText: "Search for specific class sections by code or title.",
  },
  {
    id: "teacher-classes-grid",
    targetSelector: '[data-tour="teacher-classes-grid"]',
    fallbackTargetSelector: '[data-tour="teacher-classes-header"]',
    title: "Assigned Subject Cards",
    description: "Each card displays the section name, schedule, room assignment, and total enrolled student count.",
    placement: "top",
    messageType: "tip",
    messageTitle: "Class Roster Quick View",
    messageText: "Inspect student rosters and upload learning materials per section.",
  },
  {
    id: "teacher-classes-view-btn",
    targetSelector: '[data-tour="teacher-classes-view-btn"]',
    fallbackTargetSelector: '[data-tour="teacher-classes-header"]',
    title: "View Class Details",
    description: "Click 'Proceed to View Class' to open this class section dashboard and explore student rosters, AI lesson generators, and announcements.",
    placement: "top",
    messageType: "info",
    messageTitle: "Class Detail Navigation",
    messageText: "Opens the dedicated class section dashboard.",
    actionToRoute: "auto-first-class",
    actionButtonText: "Proceed to View Class",
  },
  {
    id: "class-detail-banner",
    targetSelector: '[data-tour="teacher-class-banner"]',
    fallbackTargetSelector: 'h1',
    title: "Class Banner & Quick Metrics",
    description: "Inside the class view! Displays active subject details, section title, schedule, room, and live student/lesson metrics.",
    placement: "bottom-right",
    messageType: "info",
    messageTitle: "Class Section Dashboard",
    messageText: "Monitor class section details and activity counts.",
  },
  {
    id: "class-detail-tabs",
    targetSelector: '[data-tour="teacher-class-tabs"]',
    fallbackTargetSelector: 'h1',
    title: "Class Content Navigation Tabs",
    description: "Switch between the Students roster tab, Lessons & Learning Materials tab, and Section Announcements tab.",
    placement: "bottom-right",
    messageType: "info",
    messageTitle: "Content Navigation",
    messageText: "Manage enrolled students, AI lessons, and class notices.",
  },
  {
    id: "class-detail-students",
    targetSelector: '[data-tour="class-detail-students-list"]',
    fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
    title: "Enrolled Student Roster",
    description: "Inspect student LRNs, full names, contact info, and parent details. Search for specific students or add new section enrollments.",
    placement: "top",
    messageType: "tip",
    messageTitle: "Student Roster",
    messageText: "View enrolled student profiles and contact information.",
  },
  {
    id: "class-detail-lessons",
    targetSelector: '[data-tour="class-detail-lessons-content"]',
    fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
    title: "Lessons & AI Generator",
    description: "Create and publish structured lesson plans, upload class materials, and generate AI quiz items tailored for this section.",
    placement: "top",
    messageType: "warning",
    messageTitle: "AI Lesson & Quiz Generator",
    messageText: "Publish curriculum-aligned lessons and study resources.",
  },
  {
    id: "class-detail-announcements",
    targetSelector: '[data-tour="class-detail-announcements-content"]',
    fallbackTargetSelector: '[data-tour="teacher-class-tabs"]',
    title: "Class Announcements & Memos",
    description: "Post class notices, exam reminders, and homework assignments directly to all enrolled students in this section.",
    placement: "top",
    messageType: "info",
    messageTitle: "Section Bulletins",
    messageText: "Broadcast section-specific notices and attach file resources.",
  },

  // ─── 3. GRADES MANAGEMENT ──────────────────────────────────
  {
    id: "teacher-grades-link",
    targetSelector: '[data-tour="teacher-grades-link"]',
    title: "Grades Management & Transmutation",
    description: "Encode quarterly written work, performance tasks, and quarterly assessments. Computes DepEd transmuted grades automatically for all students.",
    placement: "right",
    messageType: "tip",
    messageTitle: "DepEd Grade Computation",
    messageText: "Click 'Next' to navigate to the Gradebook.",
    actionToRoute: "/teacher/grades",
  },
  {
    id: "teacher-grades-class-select",
    targetSelector: '[data-tour="teacher-grades-class-select"]',
    fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
    title: "Select Class Section for Grading",
    description: "Choose an assigned subject and section to load the corresponding student gradebook matrix.",
    placement: "bottom",
    messageType: "info",
    messageTitle: "Class Selector",
    messageText: "Select your active section to encode student assessment marks.",
  },
  {
    id: "teacher-grades-filters",
    targetSelector: '[data-tour="teacher-grades-filters"]',
    fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
    title: "Quarter & Assessment Filter Tabs",
    description: "Switch views between 1st–4th Quarters, filter assessment types (Quizzes, Activities, Exams), or view Passed vs Failed students.",
    placement: "bottom",
    messageType: "info",
    messageTitle: "Gradebook Matrix Filters",
    messageText: "Filter scores by academic term or assessment component.",
  },
  {
    id: "teacher-grades-table",
    targetSelector: '[data-tour="teacher-grades-table"]',
    fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
    title: "Official DepEd Gradebook Matrix",
    description: "Review auto-consolidated quarterly grades, individual assessment scores, overall percentages, and passing remarks.",
    placement: "top",
    messageType: "tip",
    messageTitle: "Transmuted Scores Matrix",
    messageText: "Computes overall grades and DepEd passing remarks automatically.",
  },
  {
    id: "teacher-grades-seatworks-eval",
    targetSelector: '[data-tour="teacher-grades-seatworks-eval"]',
    fallbackTargetSelector: '[data-tour="teacher-grades-seatworks-header"]',
    title: "Activity-Based Performance Evaluation",
    description: "Review seatworks, quizzes, performance tasks, and periodical exams. Select any seatwork or student row to inspect individual submissions.",
    placement: "right",
    messageType: "info",
    messageTitle: "Seatworks & Activities Roster",
    messageText: "Inspect seatworks and student submission statuses in real time.",
  },
  {
    id: "teacher-grades-submission-detail",
    targetSelector: '[data-tour="teacher-grades-submission-detail"]',
    fallbackTargetSelector: '[data-tour="teacher-grades-header"]',
    title: "Student Submission & Grade Evaluation",
    description: "Inspect submitted student outputs, enter or lock raw scores, write teacher feedback comments, and return grades directly to students.",
    placement: "top",
    messageType: "tip",
    messageTitle: "Score & Feedback Evaluation",
    messageText: "Input raw scores, lock grades, and return feedback to students.",
  },

  // ─── 4. SIDEBAR MODULES & ACCOUNT ──────────────────────────
  {
    id: "teacher-messages-link",
    targetSelector: '[data-tour="teacher-messages-link"]',
    title: "Direct Messages & Communication",
    description: "Communicate directly with enrolled students and school administrators via real-time messaging.",
    placement: "right",
    messageType: "tip",
    messageTitle: "DepEd Direct Messages",
    messageText: "Click 'Next' to navigate to Messages.",
    actionToRoute: "/teacher/messages",
  },
  {
    id: "teacher-messages-list",
    targetSelector: '[data-tour="teacher-messages-list"]',
    fallbackTargetSelector: '[data-tour="teacher-messages-header"]',
    title: "Conversations Roster",
    description: "Browse active student chats, class group threads, and filter by All, Unread, or Read messages.",
    placement: "right",
    messageType: "tip",
    messageTitle: "Inbox Roster",
    messageText: "Filter chats by All, Unread, or Read messages.",
  },
  {
    id: "teacher-messages-thread",
    targetSelector: '[data-tour="teacher-messages-thread"]',
    fallbackTargetSelector: '[data-tour="teacher-messages-header"]',
    title: "Interactive Chat Workspace",
    description: "View student message history, reply with text or file attachments, and track message delivery status.",
    placement: "left",
    messageType: "tip",
    messageTitle: "Live Chat Thread",
    messageText: "Send text responses and attach document resources.",
  },
  {
    id: "teacher-ai-assistant-link",
    targetSelector: '[data-tour="teacher-ai-assistant-link"]',
    title: "AI Teaching Assistant",
    description: "Leverage AI to generate complete lesson plans, quiz questions, rubrics, and interactive classroom activities tailored for Junior High School curricula.",
    placement: "right",
    messageType: "warning",
    messageTitle: "AI Copilot for Educators",
    messageText: "Generate curriculum-aligned lesson plans and quiz items in seconds.",
  },
  {
    id: "teacher-help-center-link",
    targetSelector: '[data-tour="teacher-help-center-link"]',
    title: "Teacher Help Center & Guides",
    description: "Access interactive module walkthroughs, step-by-step feature guides, FAQs, and technical support assistance anytime.",
    placement: "right",
    messageType: "info",
    messageTitle: "Help & Support Hub",
    messageText: "Replay module tours and browse FAQs whenever needed.",
  },
  {
    id: "teacher-profile-link",
    targetSelector: '[data-tour="teacher-profile-link"]',
    title: "Profile & Account Settings",
    description: "Update your contact phone number, upload your profile avatar photo, and manage your account password security.",
    placement: "right",
    messageType: "info",
    messageTitle: "Teacher Account Management",
    messageText: "Keep your contact information and login credentials up to date.",
  },
  {
    id: "teacher-notifications",
    targetSelector: '[data-tour="teacher-notifications"]',
    title: "Real-Time Notifications",
    description: "Click the bell icon anytime to check for new student messages, grade deadline reminders, and administrative alerts.",
    placement: "left",
    messageType: "info",
    messageTitle: "Notification Bell",
    messageText: "Receive instant notifications for important school updates.",
  },
  {
    id: "teacher-logout",
    targetSelector: '[data-tour="teacher-logout"]',
    title: "Logout & Session Security",
    description: "Click Logout when you finish your teaching session to safely end your session and secure student data.",
    placement: "right",
    messageType: "warning",
    messageTitle: "Session Security",
    messageText: "Always sign out when using shared school computers.",
  },
];
