export const MOCK_TOUR_DATA = {
  kpis: {
    totalClasses: 5,
    totalStudents: 42,
    publishedLessons: 18,
    draftLessons: 3,
    gradesEncodedTotal: 168,
    adminStudents: 1250,
    adminTeachers: 52,
    adminClasses: 34,
    adminSubjects: 76,
  },
  classes: [
    {
      id: "demo-class-1",
      code: "AP10",
      name: "Araling Panlipunan 10",
      section: "Grade 10 - Ruby",
      gradeLevel: "Grade 10",
      schedule: "Mon/Wed 8:00 AM - 9:30 AM",
      room: "Room 204",
      studentCount: 42,
      semester: "1st Semester SY 2026-2027",
    },
    {
      id: "demo-class-2",
      code: "MATH7",
      name: "Mathematics 7",
      section: "Grade 7 - Emerald",
      gradeLevel: "Grade 7",
      schedule: "Tue/Thu 10:00 AM - 11:30 AM",
      room: "Room 102",
      studentCount: 38,
      semester: "1st Semester SY 2026-2027",
    },
    {
      id: "demo-class-3",
      code: "SCI8",
      name: "General Science 8",
      section: "Grade 8 - Diamond",
      gradeLevel: "Grade 8",
      schedule: "Mon/Wed 1:00 PM - 2:30 PM",
      room: "Science Lab B",
      studentCount: 40,
      semester: "1st Semester SY 2026-2027",
    },
    {
      id: "demo-class-4",
      code: "ENG9",
      name: "English Literature 9",
      section: "Grade 9 - Sapphire",
      gradeLevel: "Grade 9",
      schedule: "Friday 8:00 AM - 11:00 AM",
      room: "Room 301",
      studentCount: 36,
      semester: "1st Semester SY 2026-2027",
    },
  ],
  students: [
    {
      id: "demo-stu-1",
      studentId: "108234910012",
      name: "Juan Dela Cruz",
      studentName: "Juan Dela Cruz",
      email: "juan.delacruz@deped.gov.ph",
      phone: "+63 917 123 4567",
      status: "Active",
      gradeLevel: "Grade 10",
      section: "Ruby",
      term1Grade: 88,
      term2Grade: 91,
      term3Grade: 90,
      term4Grade: 93,
      quizAverage: 92,
      activityGrade: 89,
      assignmentGrade: 90,
      examGrade: 91,
      overallGrade: 91,
      remarks: "Passed (Promoted)",
    },
    {
      id: "demo-stu-2",
      studentId: "108234910013",
      name: "Maria Santos",
      studentName: "Maria Santos",
      email: "maria.santos@deped.gov.ph",
      phone: "+63 918 234 5678",
      status: "Active",
      gradeLevel: "Grade 10",
      section: "Ruby",
      term1Grade: 94,
      term2Grade: 96,
      term3Grade: 95,
      term4Grade: 97,
      quizAverage: 96,
      activityGrade: 95,
      assignmentGrade: 96,
      examGrade: 96,
      overallGrade: 96,
      remarks: "Passed (With Honors)",
    },
    {
      id: "demo-stu-3",
      studentId: "108234910014",
      name: "John Reyes",
      studentName: "John Reyes",
      email: "john.reyes@deped.gov.ph",
      phone: "+63 919 345 6789",
      status: "Active",
      gradeLevel: "Grade 10",
      section: "Ruby",
      term1Grade: 84,
      term2Grade: 86,
      term3Grade: 88,
      term4Grade: 89,
      quizAverage: 86,
      activityGrade: 85,
      assignmentGrade: 88,
      examGrade: 87,
      overallGrade: 87,
      remarks: "Passed",
    },
    {
      id: "demo-stu-4",
      studentId: "108234910015",
      name: "Angelica Gonzales",
      studentName: "Angelica Gonzales",
      email: "angelica.gonzales@deped.gov.ph",
      phone: "+63 920 456 7890",
      status: "Active",
      gradeLevel: "Grade 10",
      section: "Ruby",
      term1Grade: 92,
      term2Grade: 93,
      term3Grade: 94,
      term4Grade: 95,
      quizAverage: 94,
      activityGrade: 93,
      assignmentGrade: 94,
      examGrade: 95,
      overallGrade: 94,
      remarks: "Passed (With Honors)",
    },
    {
      id: "demo-stu-5",
      studentId: "108234910016",
      name: "Carlos Mendoza",
      studentName: "Carlos Mendoza",
      email: "carlos.mendoza@deped.gov.ph",
      phone: "+63 921 567 8901",
      status: "Active",
      gradeLevel: "Grade 10",
      section: "Ruby",
      term1Grade: 81,
      term2Grade: 83,
      term3Grade: 85,
      term4Grade: 86,
      quizAverage: 83,
      activityGrade: 82,
      assignmentGrade: 85,
      examGrade: 84,
      overallGrade: 84,
      remarks: "Passed",
    },
  ],
  lessons: [
    {
      id: "demo-lesson-1",
      title: "Modyul 1: Kontemporaryong Isyu sa Lipunan",
      status: "Published",
      quarter: "1st Quarter",
      materialsCount: 4,
      quizzesCount: 2,
      updatedAt: "2026-07-20",
    },
    {
      id: "demo-lesson-2",
      title: "Modyul 2: Mga Suliraning Pangkapaligiran",
      status: "Published",
      quarter: "1st Quarter",
      materialsCount: 3,
      quizzesCount: 1,
      updatedAt: "2026-07-22",
    },
    {
      id: "demo-lesson-3",
      title: "Modyul 3: Paghahanda sa Kalamidad at Sakuna",
      status: "Draft",
      quarter: "1st Quarter",
      materialsCount: 2,
      quizzesCount: 1,
      updatedAt: "2026-07-25",
    },
  ],
  announcements: [
    {
      id: "demo-ann-1",
      title: "DepEd Memorandum: First Periodical Examinations Schedule",
      content: "Please be informed that the 1st Quarter Periodical Examinations for SY 2026-2027 will be conducted on August 14-15, 2026 across all grade levels.",
      createdAt: "2026-07-24T09:00:00Z",
      targetAudience: "All Teachers & Students",
      authorName: "DepEd School Principal",
    },
    {
      id: "demo-ann-2",
      title: "Class Room Orientation & Parent-Teacher Conference",
      content: "All Grade 10 section teachers are requested to finalize the 1st Quarter grade consolidation prior to the upcoming PTC meeting.",
      createdAt: "2026-07-25T14:30:00Z",
      targetAudience: "Teachers",
      authorName: "Academic Coordinator",
    },
  ],
  tasks: [
    { id: "demo-task-1", title: "Grade AP10 Seatwork 3 Submissions", dueDate: "Today", count: 42, type: "grading" },
    { id: "demo-task-2", title: "Upload Math 7 Week 4 Practice Quiz", dueDate: "Tomorrow", count: 38, type: "lesson" },
    { id: "demo-task-3", title: "Consolidate Q1 Transmuted Grades", dueDate: "In 3 Days", count: 168, type: "gradebook" },
  ],
};
