create table if not exists public.school_calendar_events (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  event_date date not null,
  event_time time,
  target_audience text not null default 'School-wide',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint school_calendar_events_target_audience_check
    check (target_audience in ('School-wide', 'Teachers', 'Students'))
);

create index if not exists school_calendar_events_event_date_idx
  on public.school_calendar_events (event_date);

create or replace function public.set_school_calendar_events_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_school_calendar_events_updated_at on public.school_calendar_events;

create trigger trg_set_school_calendar_events_updated_at
before update on public.school_calendar_events
for each row
execute function public.set_school_calendar_events_updated_at();

grant select, insert, update, delete on public.school_calendar_events to anon, authenticated;
