create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  message_text text not null,
  timestamp timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint messages_sender_receiver_check check (sender_id <> receiver_id)
);

create index if not exists messages_sender_idx
  on public.messages (sender_id);

create index if not exists messages_receiver_idx
  on public.messages (receiver_id);

create index if not exists messages_timestamp_idx
  on public.messages (timestamp desc);

create or replace function public.set_messages_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_messages_updated_at on public.messages;

create trigger trg_set_messages_updated_at
before update on public.messages
for each row
execute function public.set_messages_updated_at();

alter table if exists public.messages enable row level security;

grant select, insert, update, delete on public.messages to anon, authenticated;
grant usage, select on sequence public.messages_id_seq to anon, authenticated;

drop policy if exists messages_select_all on public.messages;
create policy messages_select_all
on public.messages
for select
to anon, authenticated
using (true);

drop policy if exists messages_insert_all on public.messages;
create policy messages_insert_all
on public.messages
for insert
to anon, authenticated
with check (true);

drop policy if exists messages_update_all on public.messages;
create policy messages_update_all
on public.messages
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists messages_delete_all on public.messages;
create policy messages_delete_all
on public.messages
for delete
to anon, authenticated
using (true);
