create table if not exists public.teacher_student_assignments (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  subject_id uuid not null references public.subjects(id) on delete cascade,
  section text,
  status text not null default 'Active',
  assigned_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint teacher_student_assignments_unique unique (teacher_id, student_id, subject_id)
);

create index if not exists teacher_student_assignments_teacher_idx
  on public.teacher_student_assignments (teacher_id);

create index if not exists teacher_student_assignments_subject_idx
  on public.teacher_student_assignments (subject_id);

create index if not exists teacher_student_assignments_student_idx
  on public.teacher_student_assignments (student_id);

create or replace function public.set_teacher_student_assignments_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_teacher_student_assignments_updated_at on public.teacher_student_assignments;

create trigger trg_set_teacher_student_assignments_updated_at
before update on public.teacher_student_assignments
for each row
execute function public.set_teacher_student_assignments_updated_at();

alter table if exists public.teacher_student_assignments enable row level security;

grant select, insert, update, delete on public.teacher_student_assignments to anon, authenticated;
grant usage, select on sequence public.teacher_student_assignments_id_seq to anon, authenticated;

drop policy if exists teacher_student_assignments_select_all on public.teacher_student_assignments;
create policy teacher_student_assignments_select_all
on public.teacher_student_assignments
for select
to anon, authenticated
using (true);

drop policy if exists teacher_student_assignments_insert_all on public.teacher_student_assignments;
create policy teacher_student_assignments_insert_all
on public.teacher_student_assignments
for insert
to anon, authenticated
with check (true);

drop policy if exists teacher_student_assignments_update_all on public.teacher_student_assignments;
create policy teacher_student_assignments_update_all
on public.teacher_student_assignments
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists teacher_student_assignments_delete_all on public.teacher_student_assignments;
create policy teacher_student_assignments_delete_all
on public.teacher_student_assignments
for delete
to anon, authenticated
using (true);
