create table if not exists public.announcements (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  target_audience text not null default 'School-wide',
  priority text not null default 'Medium',
  author text,
  created_by uuid,
  created_by_name text,
  school_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint announcements_target_audience_check
    check (target_audience in ('School-wide', 'Students', 'Teacher')),
  constraint announcements_priority_check
    check (priority in ('Low', 'Medium', 'High'))
);

create index if not exists announcements_created_at_idx
  on public.announcements (created_at desc);

create index if not exists announcements_target_audience_idx
  on public.announcements (target_audience);

create or replace function public.set_announcements_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_set_announcements_updated_at on public.announcements;

create trigger trg_set_announcements_updated_at
before update on public.announcements
for each row
execute function public.set_announcements_updated_at();

grant select, insert, update, delete on public.announcements to anon, authenticated;
grant usage, select on sequence public.announcements_id_seq to anon, authenticated;
